services:
  opreturn:
    container_name: opreturn
    image: opreturn
    build:
      context: .
      dockerfile: ./Dockerfile
#    user: "1002:1001"
    environment:
      #- LOGGING=true
      - HOST=192.168.1.3
      - PORT=28332
    ports:
      - "9090:8080"
    restart: always
#    volumes:
 #     -
